# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  plaintris-wasm:
    image: plaintris-wasm
    build:
      context: .
      dockerfile: src/PlainTris.BlazorWasmUI/Dockerfile
    ports:
      - 5025:80
