# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install wasm-tools
      run: dotnet workload install wasm-tools
    - name: Restore dependencies
      run: dotnet restore src/PlainTris.BlazorWasmUI/PlainTris.BlazorWasmUI.csproj
    - name: Build & publish project
      run: dotnet publish src/PlainTris.BlazorWasmUI/PlainTris.BlazorWasmUI.csproj -c Release --output release --nologo
      
    # changes the base-tag in index.html from '/' to 'plaintris' to match GitHub Pages repository subdirectory
    # - name: Change base-tag in index.html from / to plaintris
    #   run: sed -i 's/<base href="\/" \/>/<base href="\/plaintris\/" \/>/g' release/wwwroot/index.html
      
    # changes for segmentCount value in 404.html as appropriate for Github Pages
    #- name: Set segmentCount in 404.html
    #  run: sed -i 's/var segmentCount = 0;/var segmentCount = 1;/g' release/wwwroot/404.html

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Uploading files to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: release/wwwroot

